// AUTO-GENERATED by Trust Account Integrity Engine
// Generated: 2026-06-26
// Do not edit manually - re-run the engine to update.

import { RuleViolation, ComplianceCheck } from './types';

export const violations: RuleViolation[] = [
  {
    "id": "L021",
    "ruleId": "R01_OVERDRAWN_CLIENT_LEDGER",
    "ruleName": "Overdrawn client ledger entry",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 12(6)(a)",
    "severity": "CRITICAL",
    "evidence": "matter M016 balance -$2,500.00 NZD after entry L021 dated 2026-04-28 - client funds in deficit",
    "sourceRecordId": "L021",
    "sourceRecordType": "client_ledger",
    "description": "matter M016 balance -$2,500.00 NZD after entry L021 dated 2026-04-28 - client funds in deficit",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  },
  {
    "id": "R002",
    "ruleId": "R03_RECON_BREAK",
    "ruleName": "Reconciliation break \u2014 ledger does not equal bank balance",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 12(1)",
    "severity": "CRITICAL",
    "evidence": "period 2026-04-30: ledger_total=$798,500.00 bank_balance=$798,750.00 - bank exceeds ledger by $250.00 NZD",
    "sourceRecordId": "R002",
    "sourceRecordType": "reconciliation",
    "description": "period 2026-04-30: ledger_total=$798,500.00 bank_balance=$798,750.00 - bank exceeds ledger by $250.00 NZD",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  },
  {
    "id": "M017",
    "ruleId": "R02_DORMANT_BALANCE",
    "ruleName": "Dormant balance \u2014 no activity exceeds threshold",
    "nzLawSocietyRule": "NZLS Trust Accounting Guidelines 2024, s4.3",
    "severity": "WARNING",
    "evidence": "balance $8,500.00 NZD; last activity 2024-12-15; open 558 days (threshold 365)",
    "sourceRecordId": "M017",
    "sourceRecordType": "matter_register",
    "description": "balance $8,500.00 NZD; last activity 2024-12-15; open 558 days (threshold 365)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  },
  {
    "id": "B009",
    "ruleId": "R04_UNMATCHED_BANK_LINE",
    "ruleName": "Bank line with no matching ledger entry",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 11",
    "severity": "WARNING",
    "evidence": "bank line B009 (2026-03-28): credit=$120,000.00 debit=$0.00 - 'Credit - Schmidt purchase deposit' - no matched ledger entry; open 90 days (threshold 5)",
    "sourceRecordId": "B009",
    "sourceRecordType": "bank_statement",
    "description": "bank line B009 (2026-03-28): credit=$120,000.00 debit=$0.00 - 'Credit - Schmidt purchase deposit' - no matched ledger entry; open 90 days (threshold 5)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  },
  {
    "id": "B022",
    "ruleId": "R04_UNMATCHED_BANK_LINE",
    "ruleName": "Bank line with no matching ledger entry",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 11",
    "severity": "WARNING",
    "evidence": "bank line B022 (2026-04-30): credit=$250.00 debit=$0.00 - 'Credit - Trust account interest (Apr 2026)' - no matched ledger entry; open 57 days (threshold 5)",
    "sourceRecordId": "B022",
    "sourceRecordType": "bank_statement",
    "description": "bank line B022 (2026-04-30): credit=$250.00 debit=$0.00 - 'Credit - Trust account interest (Apr 2026)' - no matched ledger entry; open 57 days (threshold 5)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  },
  {
    "id": "B031",
    "ruleId": "R04_UNMATCHED_BANK_LINE",
    "ruleName": "Bank line with no matching ledger entry",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 11",
    "severity": "WARNING",
    "evidence": "bank line B031 (2026-05-22): credit=$15,000.00 debit=$0.00 - 'Credit - Unidentified receipt (source unknown)' - no matched ledger entry; open 35 days (threshold 5)",
    "sourceRecordId": "B031",
    "sourceRecordType": "bank_statement",
    "description": "bank line B031 (2026-05-22): credit=$15,000.00 debit=$0.00 - 'Credit - Unidentified receipt (source unknown)' - no matched ledger entry; open 35 days (threshold 5)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  },
  {
    "id": "L009",
    "ruleId": "R05_UNRECONCILED_AGEING",
    "ruleName": "Unreconciled ledger entry exceeds age threshold",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 12(1)",
    "severity": "WARNING",
    "evidence": "entry L009 (matter M008) dated 2026-03-28 is unreconciled; open 90 days (threshold 30)",
    "sourceRecordId": "L009",
    "sourceRecordType": "client_ledger",
    "description": "entry L009 (matter M008) dated 2026-03-28 is unreconciled; open 90 days (threshold 30)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  },
  {
    "id": "L011",
    "ruleId": "R07_FEE_WITHOUT_INVOICE",
    "ruleName": "Fee or disbursement entry lacks valid invoice reference",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 9",
    "severity": "WARNING",
    "evidence": "entry L011 (matter M003): description='Payment - Disbursement to beneficiary J. Williams', payment=$40,000.00, reference='' - no INV-XXXXX invoice reference found (Reg 9 breach)",
    "sourceRecordId": "L011",
    "sourceRecordType": "client_ledger",
    "description": "entry L011 (matter M003): description='Payment - Disbursement to beneficiary J. Williams', payment=$40,000.00, reference='' - no INV-XXXXX invoice reference found (Reg 9 breach)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  },
  {
    "id": "L021",
    "ruleId": "R07_FEE_WITHOUT_INVOICE",
    "ruleName": "Fee or disbursement entry lacks valid invoice reference",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 9",
    "severity": "WARNING",
    "evidence": "entry L021 (matter M016): description=\"Payment - Settlement disbursement to vendor's solicitors\", payment=$97,500.00, reference='' - no INV-XXXXX invoice reference found (Reg 9 breach)",
    "sourceRecordId": "L021",
    "sourceRecordType": "client_ledger",
    "description": "entry L021 (matter M016): description=\"Payment - Settlement disbursement to vendor's solicitors\", payment=$97,500.00, reference='' - no INV-XXXXX invoice reference found (Reg 9 breach)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  },
  {
    "id": "L035",
    "ruleId": "R07_FEE_WITHOUT_INVOICE",
    "ruleName": "Fee or disbursement entry lacks valid invoice reference",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 9",
    "severity": "WARNING",
    "evidence": "entry L035 (matter M019): description='Payment - Final disbursement of retained costs to vendor', payment=$5,000.00, reference='' - no INV-XXXXX invoice reference found (Reg 9 breach)",
    "sourceRecordId": "L035",
    "sourceRecordType": "client_ledger",
    "description": "entry L035 (matter M019): description='Payment - Final disbursement of retained costs to vendor', payment=$5,000.00, reference='' - no INV-XXXXX invoice reference found (Reg 9 breach)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-06-26",
    "actionTaken": null
  }
];

export const complianceChecks: ComplianceCheck[] = [
  {
    "id": "R01_OVERDRAWN_CLIENT_LEDGER",
    "name": "Overdrawn client ledger entry",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 12(6)(a)",
    "status": "failed",
    "resultCount": 1,
    "description": "Overdrawn client ledger entry \u2014 LCA (Trust Account) Regulations 2008, Reg 12(6)(a)"
  },
  {
    "id": "R02_DORMANT_BALANCE",
    "name": "Dormant balance \u2014 no activity exceeds threshold",
    "nzlsReference": "NZLS Trust Accounting Guidelines 2024, s4.3",
    "status": "failed",
    "resultCount": 1,
    "description": "Dormant balance \u2014 no activity exceeds threshold \u2014 NZLS Trust Accounting Guidelines 2024, s4.3"
  },
  {
    "id": "R03_RECON_BREAK",
    "name": "Reconciliation break \u2014 ledger does not equal bank balance",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 12(1)",
    "status": "failed",
    "resultCount": 1,
    "description": "Reconciliation break \u2014 ledger does not equal bank balance \u2014 LCA (Trust Account) Regulations 2008, Reg 12(1)"
  },
  {
    "id": "R04_UNMATCHED_BANK_LINE",
    "name": "Bank line with no matching ledger entry",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 11",
    "status": "failed",
    "resultCount": 3,
    "description": "Bank line with no matching ledger entry \u2014 LCA (Trust Account) Regulations 2008, Reg 11"
  },
  {
    "id": "R05_UNRECONCILED_AGEING",
    "name": "Unreconciled ledger entry exceeds age threshold",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 12(1)",
    "status": "failed",
    "resultCount": 1,
    "description": "Unreconciled ledger entry exceeds age threshold \u2014 LCA (Trust Account) Regulations 2008, Reg 12(1)"
  },
  {
    "id": "R06_FIT_OVERHELD",
    "name": "FIT balance held beyond transfer deadline",
    "nzlsReference": "NZLS Trust Accounting Guidelines 2024 / PS-2 (eff. 1 Jan 2026)",
    "status": "passed",
    "resultCount": 0,
    "description": "FIT balance held beyond transfer deadline \u2014 NZLS Trust Accounting Guidelines 2024 / PS-2 (eff. 1 Jan 2026)"
  },
  {
    "id": "R07_FEE_WITHOUT_INVOICE",
    "name": "Fee or disbursement entry lacks valid invoice reference",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 9",
    "status": "failed",
    "resultCount": 3,
    "description": "Fee or disbursement entry lacks valid invoice reference \u2014 LCA (Trust Account) Regulations 2008, Reg 9"
  }
];

export const reportSummary = {
  "totalViolations": 10,
  "criticalCount": 2,
  "highCount": 8,
  "firmName": "Coastal Law Ltd",
  "period": "May 2026",
  "generatedAt": "2026-06-26"
};
