// AUTO-GENERATED by Trust Account Integrity Engine
// Generated: 2026-07-10
// Do not edit manually - re-run the engine to update.

import { RuleViolation, ComplianceCheck } from './types';

export const violations: RuleViolation[] = [
  {
    "id": "L021",
    "ruleId": "R01_OVERDRAWN_CLIENT_LEDGER",
    "ruleName": "Overdrawn client ledger entry",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 6 and Reg 12(6)(a)",
    "severity": "CRITICAL",
    "evidence": "matter M016 balance -$2,500.00 NZD after entry L021 dated 2026-04-28 - client funds in deficit",
    "sourceRecordId": "L021",
    "sourceRecordType": "client_ledger",
    "description": "matter M016 balance -$2,500.00 NZD after entry L021 dated 2026-04-28 - client funds in deficit",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-07-10",
    "actionTaken": null
  },
  {
    "id": "R002",
    "ruleId": "R03_RECON_BREAK",
    "ruleName": "Reconciliation break \u2014 ledger does not equal bank balance",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 17 (with Reg 11)",
    "severity": "CRITICAL",
    "evidence": "period 2026-04-30: ledger_total=$798,500.00 bank_balance=$798,750.00 - bank exceeds ledger by $250.00 NZD",
    "sourceRecordId": "R002",
    "sourceRecordType": "reconciliation",
    "description": "period 2026-04-30: ledger_total=$798,500.00 bank_balance=$798,750.00 - bank exceeds ledger by $250.00 NZD",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-07-10",
    "actionTaken": null
  },
  {
    "id": "M017",
    "ruleId": "R02_DORMANT_BALANCE",
    "ruleName": "Dormant balance \u2014 no activity exceeds threshold",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 12(7); LTAG June 2024 (guidance)",
    "severity": "WARNING",
    "evidence": "balance $8,500.00 NZD; last activity 2024-12-15; open 572 days (threshold 365)",
    "sourceRecordId": "M017",
    "sourceRecordType": "matter_register",
    "description": "balance $8,500.00 NZD; last activity 2024-12-15; open 572 days (threshold 365)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-07-10",
    "actionTaken": null
  },
  {
    "id": "B031",
    "ruleId": "R04_UNMATCHED_BANK_LINE",
    "ruleName": "Bank line with no matching ledger entry",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 11",
    "severity": "WARNING",
    "evidence": "bank line B031 (2026-05-22): credit=$15,000.00 debit=$0.00 - 'Credit - Unidentified receipt (source unknown)' - no matched ledger entry; open 49 days (threshold 5)",
    "sourceRecordId": "B031",
    "sourceRecordType": "bank_statement",
    "description": "bank line B031 (2026-05-22): credit=$15,000.00 debit=$0.00 - 'Credit - Unidentified receipt (source unknown)' - no matched ledger entry; open 49 days (threshold 5)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-07-10",
    "actionTaken": null
  },
  {
    "id": "L009",
    "ruleId": "R05_UNRECONCILED_AGEING",
    "ruleName": "Unreconciled ledger entry exceeds age threshold",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 11 / Reg 17",
    "severity": "WARNING",
    "evidence": "entry L009 (matter M008) dated 2026-03-28 is unreconciled; open 104 days (threshold 30)",
    "sourceRecordId": "L009",
    "sourceRecordType": "client_ledger",
    "description": "entry L009 (matter M008) dated 2026-03-28 is unreconciled; open 104 days (threshold 30)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-07-10",
    "actionTaken": null
  },
  {
    "id": "M021",
    "ruleId": "R06_FIT_OVERHELD",
    "ruleName": "FIT balance held beyond transfer deadline",
    "nzLawSocietyRule": "LCA 2006, s110; LCA (Trust Account) Regulations 2008, Reg 8/Reg 9",
    "severity": "WARNING",
    "evidence": "FIT balance $125.00 NZD credited 2026-06-01; open 39 days (threshold 14) - transfer to office account overdue",
    "sourceRecordId": "M021",
    "sourceRecordType": "matter_register",
    "description": "FIT balance $125.00 NZD credited 2026-06-01; open 39 days (threshold 14) - transfer to office account overdue",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-07-10",
    "actionTaken": null
  },
  {
    "id": "L037",
    "ruleId": "R07_FEE_WITHOUT_INVOICE",
    "ruleName": "Fee or disbursement entry lacks valid invoice reference",
    "nzLawSocietyRule": "LCA (Trust Account) Regulations 2008, Reg 9",
    "severity": "WARNING",
    "evidence": "entry L037 (matter M012): description='Disbursement - LINZ title search fee', payment=$200.00, reference='' - no INV-XXXXX invoice reference found (Reg 9 breach)",
    "sourceRecordId": "L037",
    "sourceRecordType": "client_ledger",
    "description": "entry L037 (matter M012): description='Disbursement - LINZ title search fee', payment=$200.00, reference='' - no INV-XXXXX invoice reference found (Reg 9 breach)",
    "status": "UNRESOLVED",
    "dateIdentified": "2026-07-10",
    "actionTaken": null
  }
];

export const complianceChecks: ComplianceCheck[] = [
  {
    "id": "R01_OVERDRAWN_CLIENT_LEDGER",
    "name": "Overdrawn client ledger entry",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 6 and Reg 12(6)(a)",
    "status": "failed",
    "resultCount": 1,
    "description": "Overdrawn client ledger entry \u2014 LCA (Trust Account) Regulations 2008, Reg 6 and Reg 12(6)(a)"
  },
  {
    "id": "R02_DORMANT_BALANCE",
    "name": "Dormant balance \u2014 no activity exceeds threshold",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 12(7); LTAG June 2024 (guidance)",
    "status": "failed",
    "resultCount": 1,
    "description": "Dormant balance \u2014 no activity exceeds threshold \u2014 LCA (Trust Account) Regulations 2008, Reg 12(7); LTAG June 2024 (guidance)"
  },
  {
    "id": "R03_RECON_BREAK",
    "name": "Reconciliation break \u2014 ledger does not equal bank balance",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 17 (with Reg 11)",
    "status": "failed",
    "resultCount": 1,
    "description": "Reconciliation break \u2014 ledger does not equal bank balance \u2014 LCA (Trust Account) Regulations 2008, Reg 17 (with Reg 11)"
  },
  {
    "id": "R04_UNMATCHED_BANK_LINE",
    "name": "Bank line with no matching ledger entry",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 11",
    "status": "failed",
    "resultCount": 1,
    "description": "Bank line with no matching ledger entry \u2014 LCA (Trust Account) Regulations 2008, Reg 11"
  },
  {
    "id": "R05_UNRECONCILED_AGEING",
    "name": "Unreconciled ledger entry exceeds age threshold",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 11 / Reg 17",
    "status": "failed",
    "resultCount": 1,
    "description": "Unreconciled ledger entry exceeds age threshold \u2014 LCA (Trust Account) Regulations 2008, Reg 11 / Reg 17"
  },
  {
    "id": "R06_FIT_OVERHELD",
    "name": "FIT balance held beyond transfer deadline",
    "nzlsReference": "LCA 2006, s110; LCA (Trust Account) Regulations 2008, Reg 8/Reg 9",
    "status": "failed",
    "resultCount": 1,
    "description": "FIT balance held beyond transfer deadline \u2014 LCA 2006, s110; LCA (Trust Account) Regulations 2008, Reg 8/Reg 9"
  },
  {
    "id": "R07_FEE_WITHOUT_INVOICE",
    "name": "Fee or disbursement entry lacks valid invoice reference",
    "nzlsReference": "LCA (Trust Account) Regulations 2008, Reg 9",
    "status": "failed",
    "resultCount": 1,
    "description": "Fee or disbursement entry lacks valid invoice reference \u2014 LCA (Trust Account) Regulations 2008, Reg 9"
  }
];

export const reportSummary = {
  "totalViolations": 7,
  "criticalCount": 2,
  "highCount": 5,
  "firmName": "Coastal Law Ltd",
  "period": "May 2026",
  "generatedAt": "2026-07-10"
};
